# Generated by Django 2.2.6 on 2019-10-05 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField()),
                ('price', models.FloatField()),
                ('seller', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('car_description', models.TextField()),
                ('car_specs', models.TextField()),
            ],
        ),
    ]
