# Generated by Django 2.2.6 on 2019-10-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
