# Generated by Django 2.2.6 on 2019-10-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0002_auto_20191015_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
