# Generated by Django 2.2.6 on 2019-10-17 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0004_auto_20191016_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bulletin_board.Car')),
            ],
        ),
    ]
