# Generated by Django 2.2.6 on 2019-10-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0005_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
