# Generated by Django 2.2.6 on 2019-10-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0006_photos_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
