# Generated by Django 2.2.6 on 2019-10-19 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0007_auto_20191019_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 15, 25, 31, 743388), null=True),
        ),
    ]
