# Generated by Django 2.2.6 on 2019-10-20 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0010_auto_20191020_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 20, 15, 1, 17, 848210), null=True),
        ),
    ]
