# Generated by Django 2.2.6 on 2019-10-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0014_auto_20191022_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultimage', to='bulletin_board.Car'),
        ),
    ]
