# Generated by Django 2.2.6 on 2019-10-26 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0016_auto_20191022_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Автомобили', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='photos',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterField(
            model_name='car',
            name='avito_item',
            field=models.CharField(blank=True, max_length=100, verbose_name='Авито номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_generation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Модель авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Заголовок объявления'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(blank=True, max_length=100, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='car',
            name='doors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество дверей'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive',
            field=models.CharField(blank=True, max_length=100, verbose_name='Привод'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Тип двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AlterField(
            model_name='car',
            name='equipment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительное оборудование'),
        ),
        migrations.AlterField(
            model_name='car',
            name='modif',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модификация'),
        ),
        migrations.AlterField(
            model_name='car',
            name='owners',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество владельцев'),
        ),
        migrations.AlterField(
            model_name='car',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='car',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seller',
            field=models.CharField(blank=True, max_length=100, verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='car',
            name='steering_side',
            field=models.CharField(blank=True, max_length=100, verbose_name='Руль'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=100, verbose_name='Трансмиссия'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type_chassis',
            field=models.CharField(blank=True, max_length=100, verbose_name='Кузов'),
        ),
        migrations.AlterField(
            model_name='car',
            name='view_place',
            field=models.CharField(blank=True, max_length=100, verbose_name='Место осмотра'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='VIN номер'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Год производства'),
        ),
        migrations.AlterField(
            model_name='photos',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_images', to='bulletin_board.Car'),
        ),
    ]
