# Generated by Django 2.2.6 on 2019-10-29 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0017_auto_20191028_1549'),
        ('bulletin_board', '0017_auto_20191026_1704'),
    ]

    operations = [
    ]
