# Generated by Django 2.2.6 on 2019-11-07 04:34

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0020_auto_20191105_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_data_link',
            field=sorl.thumbnail.fields.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
