# Generated by Django 2.2.6 on 2019-11-08 11:54

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0021_auto_20191107_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_brand',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Модель авто'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.IntegerField(db_index=True, default=1971, verbose_name='Год производства'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image_data_link',
            field=sorl.thumbnail.fields.ImageField(blank=True, height_field=480, upload_to='photos/%Y/%m/%d', width_field=640),
        ),
    ]
