# Generated by Django 2.2.6 on 2019-11-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin_board', '0022_auto_20191108_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year_of_manufacture',
            field=models.IntegerField(db_index=True, null=True, verbose_name='Год производства'),
        ),
    ]
